### ISSUE TITLE
Demande de droits d'admin

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides-cli#8]
Salut @victorsalaun  !

Accepterais-tu stp de me donner les droits de mainteneur sur Pypi,
afin que je puisse faire de nouvelles releases ?

Voici mon username : https://pypi.org/user/LucasC/

**Comment by victorsalaun** [comment]
Hello @Lucas-C 
c'est fait :)

**Comment by Lucas-C** [comment]
Merci beaucoup !

**Comment by Lucas-C** [comment]
Release faite : https://github.com/voyages-sncf-technologies/hesperides-cli/releases/tag/v0.3.2
